In [1]:
import tensorflow as tf

import numpy as np



# 声明一个常量的张量值

x_constant = tf.constant(np.arange(24).reshape((2,3,4)), name="x_constant")

print(x_constant)

## out: Tensor("x_constant:0", shape=(2, 3, 4), dtype=int64)



# 声明一个使用shape=(3,4,5,6)，并使用高斯分布随机生成的张量

x_normal = tf.random_normal(shape=(3,4,5,6),mean=1,stddev=2,name="x_normal")

print(x_normal)

## out: Tensor("x_normal:0", shape=(3, 4, 5, 6), dtype=float32)

Tensor("x_constant:0", shape=(2, 3, 4), dtype=int32)
Tensor("x_normal:0", shape=(3, 4, 5, 6), dtype=float32)


In [2]:
x_1 = tf.random_normal((2,3,4), name = "x_1")

x_2 = tf.random_normal((2,3,4), name = "x_2")

y_1 = x_1 + x_2

y_2 = x_1 * x_2

In [3]:
sess = tf.Session()

y_1_value, y_2_value = sess.run([y_1,y_2])

print(y_1_value, y_2_value)

[[[-0.61028773  0.75173205 -0.72970086  1.43277884]
  [-1.35753989  0.87805808  1.47558367 -0.9240306 ]
  [-1.51184285  0.87371409 -2.01186013 -1.8025496 ]]

 [[ 1.52335048  1.29091835  1.85609436  0.92740381]
  [-0.26803267  1.57953    -0.33360711  1.57216525]
  [-0.72763556  2.98807955 -0.61161888 -1.13236547]]] [[[ 0.0547506   0.14095654 -0.73608446  0.2658588 ]
  [ 0.45810515  0.16609988  0.48116279  0.060644  ]
  [ 0.45093647 -0.27253506  0.92523855  0.59524012]]

 [[ 0.19785354 -0.29955834  0.77501404  0.14583713]
  [-0.1654695  -0.34484145 -0.02089558  0.2716434 ]
  [-0.64418447  2.0688467   0.08480736 -1.12360716]]]


In [4]:
logDir = "./TensorBoard"

train_writer = tf.summary.FileWriter(logDir,sess.graph)
train_writer.close()

